<?php
    header('Content-Type: application/xml; charset=utf-8');

    require_once('Json2XML.class.php');

    $json = '{"COR": "PRATA", "IPVA": "0,00", "TIPO": "CAMINHONETE", "DPVAT": "NADA CONSTA", "MOTOR": "552616748951028", "PLACA": "FVX7B97", "CHASSI": "98822617CMKD34694", "DEBDER": "0,00", "MODELO": "FIAT/TORO VOLCANO AT9 D4", "ANOFABR": "2020", "RENAVAM": "01235247632", "DEBDERSA": "0,00", "SITUACAO": "CIRCULACAO", "ANOMODELO": "2021", "CATEGORIA": "PARTICULAR", "DATAVENDA": "NAO INFORMADO", "DEBCETESB": "0,00", "DEBDETRAN": "0,00", "MUNICIPIO": "SUMARE - SP", "DEBRENAINF": "0,00", "NOMEAGENTE": "", "RESRENAJUD": "NAO CONSTA BLOQUEIO JUDICIAL - RENAJUD", "COMBUSTIVEL": "DIESEL", "NOME_AGENTE": "NADA CONSTA", "PROCEDENCIA": "NACIONAL", "RESJUDICIAL": "NAO INFORMADO", "ARRENDATARIO": "NADA CONSTA", "PROPRIETARIO": "ALESSANDRO PARRIAO RODRIGUES EMPILHADEIRAS", "DEBMUNICIPAIS": "260,32", "DOC_COMPRADOR": "NAO INFORMADO", "LICENCIAMENTO": "14/08/2020", "RESTRIBUTARIA": "NAO INFORMADO", "CPFCNPJ_FINANC": "NADA CONSTA", "PRONOMEANTERIOR": "FCA FIAT CHRYSLER AUTOMOVEIS BRASIL LTDA", "BLOQUEIO_GUINCHO": "NAO INFORMADO", "COMUNICACAOVENDA": "NAO CONSTA COMUNICACAO DE VENDAS", "RESADMINISTRATIVA": "NADA CONSTA", "TIPO_DOC_COMPRADOR": "NAO INFORMADO", "OUTRAS_RESTRICOES_01": "NADA CONSTA", "OUTRAS_RESTRICOES_02": "VEICULO COM INSPECAO VEICULAR OK", "OUTRAS_RESTRICOES_03": "NADA CONSTA", "OUTRAS_RESTRICOES_04": "NADA CONSTA", "OUTRAS_RESTRICOES_05": "NADA CONSTA", "OUTRAS_RESTRICOES_06": "NADA CONSTA", "RESTRICAO_FINANCEIRA": "NADA CONSTA", "INCLUSAO_FINANCIAMENTO": "NADA CONSTA", "ARRENDATARIO_FINANCIADO": "NADA CONSTA"}';

    $json2xml = new Json2XML();
    $xml = $json2xml->convert($json, 'DEBITOS');
    echo $xml;
?>